[package]
name = "sm2"
version = "0.0.1"
authors = ["github@manhtai.com"]
edition = "2018"

[lib]
name = "sm2"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
chrono = { version = "0.4" }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1"